name: Publisher
on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.ACTIONS_PAT }}"
      - uses: anatawa12/something-releaser@v2

      - run: set-git-user anatawa12-bot

      - name: Update Version
        id: up
        run: |
          # set current version
          VERSION="$(get-version)"
          if ! [[ "$VERSION" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi
          VERSION="$(version-stable "$VERSION")"
          set-version "$VERSION"
          # commit & tag
          git add .
          git commit -m "v$VERSION"
          git tag "v$VERSION"
          git push && git push --tags


      - name: Create New Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sleep 1
          gh release create "v$(get-version)"

      - name: Update To Next Version
        run: |
          VERSION="$(get-version)"
          VERSION="$(version-next "$VERSION")"
          set-version "$(version-snapshot "$VERSION")"
          git add .
          git commit -m "prepare for next version: $VERSION"
          git push
